REATE TYPE IF NOT EXISTS STATUS_FRIENDSHIP AS ENUM ('approved', 'not_approved');
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS FILMS CASCADE;
DROP TABLE IF EXISTS USERS_LIKE_FILMS CASCADE;
DROP TABLE IF EXISTS FILMS_GENRES CASCADE;
DROP TABLE IF EXISTS RATING_MPA CASCADE;
DROP TABLE IF EXISTS GENRES CASCADE;
DROP TABLE IF EXISTS FRIENDSHIP CASCADE;

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS
(
    ID
    BIGINT
    NOT
    NULL
    AUTO_INCREMENT,
    TITLE
    varchar
(
    127
) NOT NULL UNIQUE,
    DESCRIPTION varchar
(
    200
) UNIQUE,
    RELEASE_DATE DATE,
    DURATION INTEGER NOT NULL,
    mpa INTEGER NOT NULL,
    CONSTRAINT FILMS_PK PRIMARY KEY
(
    ID
)
    );
CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID
    BIGINT
    NOT
    NULL
    AUTO_INCREMENT,
    email
    varchar
(
    255
) NOT NULL UNIQUE,
    login varchar
(
    31
) NOT NULL UNIQUE,
    name varchar
(
    31
) NOT NULL,
    birthday DATE,
    CONSTRAINT USERS_PK PRIMARY KEY
(
    ID
)
    );
CREATE TABLE IF NOT EXISTS PUBLIC.RATING_MPA
(
    ID
    INTEGER
    NOT
    NULL
    AUTO_INCREMENT,
    TITLE
    varchar
(
    10
) NOT NULL UNIQUE,
    CONSTRAINT RATING_MPA_PK PRIMARY KEY
(
    ID
)
    );
ALTER TABLE FILMS
    ADD CONSTRAINT IF NOT EXISTS FILMS_FK FOREIGN KEY (mpa) REFERENCES RATING_MPA (ID) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES
(
    ID
    INTEGER
    NOT
    NULL
    AUTO_INCREMENT,
    TITLE
    VARCHAR
(
    63
) NOT NULL UNIQUE,
    CONSTRAINT GENRES_PK PRIMARY KEY
(
    ID
)
    );
CREATE TABLE IF NOT EXISTS PUBLIC.FILMS_GENRES
(
    FILM_ID
    BIGINT
    NOT
    NULL,
    GENRE_ID
    INTEGER
    NOT
    NULL,
    CONSTRAINT
    FILMS_GENRES_FK
    FOREIGN
    KEY
(
    FILM_ID
) REFERENCES PUBLIC.FILMS
(
    ID
) ON DELETE CASCADE
  ON UPDATE CASCADE,
    CONSTRAINT FILMS_GENRES_FK_1 FOREIGN KEY
(
    GENRE_ID
) REFERENCES PUBLIC.GENRES
(
    ID
)
  ON DELETE CASCADE
  ON UPDATE CASCADE
    );
CREATE TABLE IF NOT EXISTS PUBLIC.USERS_LIKE_FILMS
(
    USER_ID
    BIGINT
    NOT
    NULL,
    FILM_ID
    BIGINT
    NOT
    NULL,
    CONSTRAINT
    USERS_LIKE_FILMS_PK
    PRIMARY
    KEY
(
    USER_ID,
    FILM_ID
),
    CONSTRAINT USER_LIKE_FILMS_FK FOREIGN KEY
(
    USER_ID
) REFERENCES PUBLIC.USERS
(
    ID
) ON DELETE CASCADE
  ON UPDATE CASCADE,
    CONSTRAINT USER_LIKE_FILMS_FK_1 FOREIGN KEY
(
    FILM_ID
) REFERENCES PUBLIC.FILMS
(
    ID
)
  ON DELETE CASCADE
  ON UPDATE CASCADE
    );
CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP
(
    USER_WHO_SEND_ID
    BIGINT
    NOT
    NULL,
    USER_MUST_CONFIRM_ID
    BIGINT
    NOT
    NULL,
    STATUS
    VARCHAR
(
    63
) NOT NULL,
    CONSTRAINT FRIENDSHIP_PK PRIMARY KEY
(
    USER_WHO_SEND_ID,
    USER_MUST_CONFIRM_ID
),
    CONSTRAINT FRIENDSHIP_FK FOREIGN KEY
(
    USER_WHO_SEND_ID
) REFERENCES PUBLIC.USERS
(
    ID
) ON DELETE CASCADE
  ON UPDATE CASCADE,
    CONSTRAINT FRIENDSHIP_FK_1 FOREIGN KEY
(
    USER_MUST_CONFIRM_ID
) REFERENCES PUBLIC.USERS
(
    ID
)
  ON DELETE CASCADE
  ON UPDATE CASCADE
    );
INSERT INTO GENRES (TITLE)
VALUES ('Комедия');
INSERT INTO GENRES (TITLE)
VALUES ('Драма');
INSERT INTO GENRES (TITLE)
VALUES ('Мультфильм');
INSERT INTO GENRES (TITLE)
VALUES ('Триллер');
INSERT INTO GENRES (TITLE)
VALUES ('Документальный');
INSERT INTO GENRES (TITLE)
VALUES ('Боевик');

INSERT INTO RATING_MPA (TITLE)
VALUES ('G');
INSERT INTO RATING_MPA (TITLE)
VALUES ('PG');
INSERT INTO RATING_MPA (TITLE)
VALUES ('PG-13');
INSERT INTO RATING_MPA (TITLE)
VALUES ('R');
INSERT INTO RATING_MPA (TITLE)
VALUES ('NC-17');
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Крадущийся тигр затаившийся дракон', 'описание Крадущийся тигр затаившийся дракон', '2003-03-03', 120, 3);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Как приручить дракона', 'описание Как приручить дракона', '2011-11-11', 160, 2);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Смешарики', 'описание Смешарики', '2013-06-06', 160, 1);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('99 франков', 'описание 99 франков', '2000-01-01', 200, 4);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Карты деньги 2 ствола', 'описание Карты деньги 2 ствола', '2000-10-10', 150, 5);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Звездные войны', 'описание Звездные войны', '2000-01-01', 210, 3);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Исчезнувшая', 'описание Исчезнувшая', '2014-01-01', 190, 4);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Кот в сапогах', 'описание Кот в сапогах', '2021-04-21', 180, 2);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Джанго', 'описание Джанго', '1999-04-21', 170, 5);
INSERT INTO FILMS(TITLE, DESCRIPTION, RELEASE_DATE, DURATION, mpa)
VALUES ('Мои маленькие пони', 'описание Мои маленькие пони', '2007-07-17', 30, 1);

INSERT INTO USERS (email, login, name, birthday)
VALUES ('mail@mail2.ru', 'login', 'name', '1990-02-01');
INSERT INTO USERS (email, login, name, birthday)
VALUES ('mail@mail3.ru', 'Хитрая выхухоль', 'Зина', '1991-12-11');
INSERT INTO USERS (email, login, name, birthday)
VALUES ('mail@mail4.ru', 'Дарт Вейдер', 'Энакин', '1992-07-11');
INSERT INTO USERS (email, login, name, birthday)
VALUES ('mail@mail5.ru', 'Бараш', 'Иннокентий', '1993-08-10');
INSERT INTO USERS (email, login, name, birthday)
VALUES ('mail@mail6.ru', 'Мыр', 'фаня', '1994-08-04');
INSERT INTO USERS (email, login, name, birthday)
VALUES ('mail@mail63.ru', 'Искорка', 'искорка', '2012-01-01');

INSERT INTO FILMS_GENRES
VALUES (1, 2);
INSERT INTO FILMS_GENRES
VALUES (1, 6);
INSERT INTO FILMS_GENRES
VALUES (2, 3);
INSERT INTO FILMS_GENRES
VALUES (2, 1);
INSERT INTO FILMS_GENRES
VALUES (3, 1);
INSERT INTO FILMS_GENRES
VALUES (3, 3);
INSERT INTO FILMS_GENRES
VALUES (4, 2);
INSERT INTO FILMS_GENRES
VALUES (5, 6);
INSERT INTO FILMS_GENRES
VALUES (6, 2);
INSERT INTO FILMS_GENRES
VALUES (6, 6);
INSERT INTO FILMS_GENRES
VALUES (7, 2);
INSERT INTO FILMS_GENRES
VALUES (8, 3);
INSERT INTO FILMS_GENRES
VALUES (9, 6);
INSERT INTO FILMS_GENRES
VALUES (10, 3);

INSERT INTO FRIENDSHIP
VALUES (1, 2, 'approved');
INSERT INTO FRIENDSHIP
VALUES (2, 3, 'not_approved');
INSERT INTO FRIENDSHIP
VALUES (3, 4, 'approved');
INSERT INTO FRIENDSHIP
VALUES (4, 5, 'not_approved');
INSERT INTO FRIENDSHIP
VALUES (5, 6, 'approved');
INSERT INTO FRIENDSHIP
VALUES (6, 1, 'not_approved');
INSERT INTO FRIENDSHIP
VALUES (6, 2, 'approved');

INSERT INTO USERS_LIKE_FILMS
VALUES (1, 1);
INSERT INTO USERS_LIKE_FILMS
VALUES (1, 5);
INSERT INTO USERS_LIKE_FILMS
VALUES (2, 2);
INSERT INTO USERS_LIKE_FILMS
VALUES (3, 3);
INSERT INTO USERS_LIKE_FILMS
VALUES (4, 4);
INSERT INTO USERS_LIKE_FILMS
VALUES (5, 5);
INSERT INTO USERS_LIKE_FILMS
VALUES (6, 6);
INSERT INTO USERS_LIKE_FILMS
VALUES (2, 7);
INSERT INTO USERS_LIKE_FILMS
VALUES (3, 8);
INSERT INTO USERS_LIKE_FILMS
VALUES (3, 9);
INSERT INTO USERS_LIKE_FILMS
VALUES (4, 3);
INSERT INTO USERS_LIKE_FILMS
VALUES (6, 7);
